#!/usr/bin/env python3

import argparse
parser = argparse.ArgumentParser(description='Toggles SW Prefetching')

parser.add_argument('-son', '--softwarePrefetcherOn', action="store_true", help='Turn on Software Prefetching in workloads')

args = parser.parse_args()

sw_pref = False
if args.softwarePrefetcherOn:
    sw_pref = True

seqDefs_path = "/home/jayasri/fall-2025-sem1/ug-rd/pbbsbench-fall-2025/benchmarks/nearestNeighbors/bench/common/seqDefs"
parallelDefs_path = "/home/jayasri/fall-2025-sem1/ug-rd/pbbsbench-fall-2025/benchmarks/nearestNeighbors/bench/common/parallelDefs"

def prefetch_toggle(sw_pref, path):
    prefetch_knob = " -DPREFETCH_ENABLE"
    with open(path, 'r') as f:
        lines = f.readlines()

    for i in range(len(lines)-1, -1, -1):
        if "CFLAGS" in lines[i]: 
            temp = lines[i][:lines[i].rindex(')')+1]
            if sw_pref:
                temp = temp + prefetch_knob
            lines[i] = temp + '\n'
            break

    with open(path, 'w') as f1:
        f1.writelines(lines)

toggle = "On" if sw_pref else "Off"

prefetch_toggle(sw_pref, seqDefs_path)
prefetch_toggle(sw_pref, parallelDefs_path)

print("Done: Software Prefetchers turned " + toggle + " ...")

            
